version: 2
jobs:
  build:
    working_directory: ~/odedlaz/oded.blog
    shell: /bin/bash --login
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run: yarn global add gulp
      - run: yarn global upgrade --latest
      - run: yarn upgrade --latest
      - run: git config --global user.name "CircleCI"
      - run: git config --global user.email "ci@oded.blog"
      - save_cache:
         key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
         paths:
            - node_modules/
workflows:
   version: 2
   pre:
      jobs:
         - build
