# Menus
menu:
  Keys: crypto-keys
  About: whoami

# Customize
customize:
    logo:
        enabled: false
        width: 40
        height: 40
        url:
    profile:
        enabled: true # Whether to show profile bar
        avatar: /images/logo.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Oded Lazar
        author_title: I code during the day, and think about the bugs I created at night.
        location: Tel Aviv, Israel
        follow: https://github.com/odedlaz
    highlight: github
    sidebar: right # sidebar position, options: left, right or leave it empty
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: https://github.com/odedlaz
        facebook: https://facebook.com/oded.blog
        linkedin: https://linkedin.com/in/odedlaz
        rss: https://oded.blog/atom.xml
        # twitter: https://twitter.com/odedlaz
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - tagcloud
    - category

# Search
search:
    insight: true # depends on 'hexo-generator-json-content'
    swiftype: # enter swiftype install key

# Comment
comment:
    disqus: # thoughts-data-bugs
    isso: # isso.oded.blog
    facebook: # enter app id
    gitment:
        owner: odedlaz
        repo: oded.blog.comments
        client_id: c0d55076889ae2a8f33d
        client_secret: i<3hummus

# Plugins
plugins:
    google_analytics: # UA-91802969-1 # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    mathjax: false # options: true, false
    katex: true # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
